name: "Coverage & Testing Workflow"

on:
  pull_request:
    types:
      - opened
    branches:
      - main

jobs:
  semver:
    runs-on: ubuntu-latest
    outputs:
      current: ${{ steps.version.outputs.version }} 
      previous: ${{ steps.version.outputs.previous-version }} 
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}   # checkout the correct branch name
          fetch-depth: 0                # fetch the whole repo history

      - name: Git Version
        id: version
        uses: codacy/git-version@2.7.1

  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions-rs/toolchain@v1
        name: install rust toolchain
        with:
          toolchain: nightly
          override: true

      - uses: actions-rs/grcov@v0.1

      - name: Run cargo-tarpaulin
        uses: actions-rs/tarpaulin@v0.1
        with:
          version: '0.15.0'
          args: '-- --test-threads 1'

      - name: Load secret
        uses: 1password/load-secrets-action@v2
        with:
          # Export loaded secrets as environment variables
          export-env: true
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
          CODECOV_TOKEN: op://${{ env.OPW_VAULT }}/codecov/api_token

      - name: Upload to codecov.io
        uses: codecov/codecov-action@v1.0.2
        with:
          token: ${{ env.CODECOV_TOKEN }}

      - name: Load secret
        uses: 1password/load-secrets-action@v2
        with:
          # Remove local copies of the Docker credentials, which are not needed anymore
          unset-previous: true
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}

      - name: Archive code coverage results
        uses: actions/upload-artifact@v1
        with:
          name: code-coverage-report
          path: cobertura.xml

  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions-rs/toolchain@v1
        name: install rust toolchain
        with:
          toolchain: nightly
          override: true

      - uses: actions-rs/cargo@v1
        name: run cargo fmt
        with:
          command: fmt

      - uses: actions-rs/cargo@v1
        name: run cargo clippy
        with:
          command: clippy

  testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions-rs/toolchain@v1
        name: install rust toolchain
        with:
          toolchain: nightly
          override: true

      - uses: actions-rs/cargo@v1
        name: run cargo fmt
        with:
          command: fmt

      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all-features --no-fail-fast
        env:
          CARGO_INCREMENTAL: '0'
          RUSTFLAGS: '-Zprofile -Ccodegen-units=1 -Cinline-threshold=0 -Clink-dead-code -Coverflow-checks=off -Cpanic=abort -Zpanic_abort_tests'
          RUSTDOCFLAGS: '-Zprofile -Ccodegen-units=1 -Cinline-threshold=0 -Clink-dead-code -Coverflow-checks=off -Cpanic=abort -Zpanic_abort_tests'

  documentation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions-rs/toolchain@v1
        name: install rust toolchain
        with:
          toolchain: nightly
          override: true

      - uses: actions-rs/cargo@v1
        name: run cargo doc
        with:
          command: doc

  benchmark:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions-rs/toolchain@v1
        name: install rust toolchain
        with:
          toolchain: nightly
          override: true

      - uses: actions-rs/cargo@v1
        name: run cargo bench
        with:
          command: bench

      - name: Run cargo bloat
        uses: orf/cargo-bloat-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions-rs/toolchain@v1
        name: install rust toolchain
        with:
          toolchain: nightly
          override: true

      - uses: actions-rs/audit-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}